source "https://rubygems.org"
ruby "2.5.1"

gem "active_model_serializers", ">= 0.10.12"
gem "bunny"
gem "delayed_job_active_record", ">= 4.1.5"
gem "delayed_job", ">= 4.1.9"
gem "devise", ">= 4.7.0"
gem "discard", ">= 1.1.0"
gem "figaro"
gem "fog-google"
gem "font-awesome-rails", ">= 4.7.0.6"
gem "foreman"
gem "jwt"
gem "mutations", ">= 0.8.3"
gem "paperclip", ">= 6.1.0"
gem "pg"
gem "polymorphic_constraints"
gem "rack-attack"
gem "rack-cors"
gem "rails_12factor"
gem "rails", ">= 6.1.7.5"
gem "request_store"
gem "rollbar"
gem "scenic", ">= 1.5.0"
gem "secure_headers"
gem "skylight", ">= 3.0.0"
gem "tzinfo" # For validation of user selected timezone names
gem "valid_url"
gem "webpack-rails"
# Still working out the bugs. - RC 5 Jul 18
gem "rabbitmq_http_api_client"
gem "zero_downtime_migrations"

group :development, :test do
  gem "thin"
  gem "capybara"
  gem "codecov", require: false
  gem "database_cleaner"
  gem "factory_bot_rails", ">= 4.11.0"
  gem "faker"
  gem "hashdiff"
  gem "letter_opener"
  gem "lol_dba", ">= 2.2.0"
  gem "pry-rails"
  gem "pry"
  gem "rails-erd", ">= 1.6.0"
  gem "rspec-rails", ">= 3.8.0"
  gem "rspec"
  gem "selenium-webdriver"
  gem "simplecov"
  gem "smarf_doc", git: "https://github.com/RickCarlino/smarf_doc.git"
end

group :production do
  gem "passenger"
end
